### ISSUE TITLE
I want to obtain code representation vectors of my own source code data 

### ISSUE THREAD

**Issue by HosoyaKenn** [zkcpku/HiT-hierarchy-transformer#1] opened 2023-04-04 12:01 UTC
I want to obtain code representation vectors of my own source code data through your code. Can I do this without downstream tasks? If not, my own task is closer to code classification. Could you please tell me about how to obtain the file of code representation vectors?

**Comment by zkcpku** [comment] 2023-04-06 01:26
Unfortunately, we didn't have the opportunity to pre-train the model, which implies that we may not be able to provide you with an appropriate parameter to generate general code representation vectors. However, you can still consider using your own data to train the model for the code classification task. 
A few changes in the code may be needed. 
I would like to highlight that the data processing component is located at this link: https://github.com/zkcpku/HiT-hierarchy-transformer/blob/fdb27a4fdc1bdecd25621b3d6a35fc5a3a4da5c9/classification/processed_tokens_with_path.py#L21
In addition, the code for model initialization and training can be found here: https://github.com/zkcpku/HiT-hierarchy-transformer/blob/fdb27a4fdc1bdecd25621b3d6a35fc5a3a4da5c9/classification/run_HiT.py#L560
Finally, once the training is complete, you can obtain the code representation vectors by extracting the vectors at this link: https://github.com/zkcpku/HiT-hierarchy-transformer/blob/fdb27a4fdc1bdecd25621b3d6a35fc5a3a4da5c9/classification/model/HiT.py#L71

**Comment by HosoyaKenn** [comment] 2023-04-08 06:45
Thank you, I am trying to run it, but it prompts the following issues. 
![Screenshot from 2023-04-08 14-42-41](https://user-images.githubusercontent.com/62983214/230707549-ae5da1a0-46ce-4e10-8e0d-f506e872d30d.png)
Could you share your "treesitter_tools" folder?

**Comment by zkcpku** [comment] 2023-04-08 08:09
> Thank you, I am trying to run it, but it prompts the following issues. ![Screenshot from 2023-04-08 14-42-41](https://user-images.githubusercontent.com/62983214/230707549-ae5da1a0-46ce-4e10-8e0d-f506e872d30d.png) Could you share your "treesitter_tools" folder?

The file structure has been modified slightly on Github. You can refer to this file:
https://github.com/zkcpku/HiT-hierarchy-transformer/blob/master/classification/treesitter2anytree.py#L69

**Comment by HosoyaKenn** [comment] 2023-04-08 08:28
There are still missing relevant files.
anytree tree-sitter and csn_parsers.so
![Screenshot from 2023-04-08 16-23-43](https://user-images.githubusercontent.com/62983214/230711741-6774ecc2-1c74-42e9-a477-4f785580a77f.png)

**Comment by zkcpku** [comment] 2023-04-08 08:33
> There are still missing relevant files. anytree tree-sitter and csn_parsers.so ![Screenshot from 2023-04-08 16-23-43](https://user-images.githubusercontent.com/62983214/230711741-6774ecc2-1c74-42e9-a477-4f785580a77f.png)

`anytree` and `tree_sitter` are both third-party libraries for Python. You can install them on your own. `parser.so` is a built library used by the treesitter library. You can find detailed information at https://github.com/tree-sitter/py-tree-sitter#setup.

**Comment by HosoyaKenn** [comment] 2023-04-08 09:51
![Screenshot from 2023-04-08 17-49-33](https://user-images.githubusercontent.com/62983214/230714955-abdd79cf-ef9d-44bb-bc34-b00fadef2dc7.png)
Is there any error in the running command?

**Comment by zkcpku** [comment] 2023-04-08 10:08
> ![Screenshot from 2023-04-08 17-49-33](https://user-images.githubusercontent.com/62983214/230714955-abdd79cf-ef9d-44bb-bc34-b00fadef2dc7.png) Is there any error in the running command?

I have reviewed my code and found no errors. Can you confirm if the config name "Transformer_java_Train_HiT" is located correctly on the following lines of the code?
https://github.com/zkcpku/HiT-hierarchy-transformer/blob/master/classification/config.py#L110
https://github.com/zkcpku/HiT-hierarchy-transformer/blob/master/classification/config.py#L588


The logic in `config.py` is that it will check the last args in the program command line, (which is "Transformer_java_Train_HiT"), and match its name to the corresponding config class, assigning it to the variable "my_config". 
One possible solution is for you to check the "all_choose_dict" dict, and make sure it includes "Transformer_java_Train_HiT". Or you can directly set `my_config = Transformer_java_Train_HiT()`

Maybe I might know where the problem is. We changed the capitalization of the class name from 'Java' to 'java' in the config. I apologize for any confusion it might have caused for you.

**Comment by zkcpku** [comment] 2023-04-08 10:19
By the way, I notice you may use the absolute hierarchy (referred to as "global hierarchy" in the paper). You can change it to "whole" at:
https://github.com/zkcpku/HiT-hierarchy-transformer/blob/5ab1ddc30e0af5c65ebec3f2659ab3efa37360a3/classification/run_HiT.py#L44

**Comment by HosoyaKenn** [comment] 2023-04-08 11:07
Thank you. I found it was a case sensitivity issue（'Java' / 'java'）. Another problem is that is this file missing? The 'pkl' file was not generated when executing 'code_classfication_preprocess.py' and 'python processed_tokens_with_path.py'.
![Screenshot from 2023-04-08 18-53-53](https://user-images.githubusercontent.com/62983214/230717875-179b226a-e562-4188-b72d-42fb05c2fad7.png)

**Comment by zkcpku** [comment] 2023-04-08 11:18
> Thank you. I found it was a case sensitivity issue（'Java' / 'java'）. Another problem is that is this file missing? The 'pkl' file was not generated when executing 'code_classfication_preprocess.py' and 'python processed_tokens_with_path.py'. ![Screenshot from 2023-04-08 18-53-53](https://user-images.githubusercontent.com/62983214/230717875-179b226a-e562-4188-b72d-42fb05c2fad7.png)

You can use the https://github.com/zkcpku/HiT-hierarchy-transformer/blob/master/classification/generate_vocab.py to process your vocab, along with the utils.vocab https://github.com/zkcpku/HiT-hierarchy-transformer/blob/master/variable%20scope%20detection/utils/vocab.py

**Comment by HosoyaKenn** [comment] 2023-04-08 12:42
Do you know how this problem occurred?
![Screenshot from 2023-04-08 20-42-17](https://user-images.githubusercontent.com/62983214/230721701-b84d0d2b-546b-4e84-88e9-2bfc46adbe80.png)

**Comment by zkcpku** [comment] 2023-04-08 12:49
> Do you know how this problem occurred? ![Screenshot from 2023-04-08 20-42-17](https://user-images.githubusercontent.com/62983214/230721701-b84d0d2b-546b-4e84-88e9-2bfc46adbe80.png)

You can check here https://github.com/zkcpku/HiT-hierarchy-transformer/blob/master/classification/run_HiT.py#L197.
The function name should be __getitem__. 

This is because we made a typo while doing a global replacement during the code upload process by changing the model name from TiT to HiT.

**Comment by HosoyaKenn** [comment] 2023-04-09 12:01
Thank you for your patient reply. I have implemented what I need.

**Comment by zkcpku** [comment] 2023-04-09 12:06
> Thank you for your patient reply. I have implemented what I need.

Thanks for your appreciate for our work! Feel free to contact me if you meet any questions.

**Closed as completed by zkcpku** 2023-04-09 12:06 UTC
